
[theme]
base="dark"
primaryColor="#00BFA6"
backgroundColor="#0E1117"
secondaryBackgroundColor="#161B22"
textColor="#FAFAFA"
font="sans serif"

[server]
headless=true
enableCORS=false
enableXsrfProtection=false